/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as SignupIndexImport } from './routes/signup/index'
import { Route as RecordIndexImport } from './routes/record/index'
import { Route as ProfileIndexImport } from './routes/profile/index'
import { Route as MyRequestsIndexImport } from './routes/my-requests/index'
import { Route as LoginIndexImport } from './routes/login/index'
import { Route as HistoryIndexImport } from './routes/history/index'
import { Route as GpsIndexImport } from './routes/gps/index'
import { Route as DashboardIndexImport } from './routes/dashboard/index'
import { Route as PortfolioIdImport } from './routes/portfolio/$id'
import { Route as HistoryItemImport } from './routes/history/$item'
import { Route as GpsPortfolioPage } from './routes/gps/$gps-portfolio'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const GpsPortfolioPage = GpsPortfolioPage.update({
  id: '/gps/$gps-portfolio',
  path: '/gps/$gps-portfolio',
  getParentRoute: () => rootRoute,
} as any)

const SignupIndexRoute = SignupIndexImport.update({
  id: '/signup/',
  path: '/signup/',
  getParentRoute: () => rootRoute,
} as any)

const RecordIndexRoute = RecordIndexImport.update({
  id: '/record/',
  path: '/record/',
  getParentRoute: () => rootRoute,
} as any)

const ProfileIndexRoute = ProfileIndexImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => rootRoute,
} as any)

const MyRequestsIndexRoute = MyRequestsIndexImport.update({
  id: '/my-requests/',
  path: '/my-requests/',
  getParentRoute: () => rootRoute,
} as any)

const LoginIndexRoute = LoginIndexImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRoute,
} as any)

const HistoryIndexRoute = HistoryIndexImport.update({
  id: '/history/',
  path: '/history/',
  getParentRoute: () => rootRoute,
} as any)

const GpsIndexRoute = GpsIndexImport.update({
  id: '/gps/',
  path: '/gps/',
  getParentRoute: () => rootRoute,
} as any)

const DashboardIndexRoute = DashboardIndexImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRoute,
} as any)

const PortfolioIdRoute = PortfolioIdImport.update({
  id: '/portfolio/$id',
  path: '/portfolio/$id',
  getParentRoute: () => rootRoute,
} as any)

const HistoryItemRoute = HistoryItemImport.update({
  id: '/history/$item',
  path: '/history/$item',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/history/$item': {
      id: '/history/$item'
      path: '/history/$item'
      fullPath: '/history/$item'
      preLoaderRoute: typeof HistoryItemImport
      parentRoute: typeof rootRoute
    }
    '/gps/$gps-portfolio': {
      id: '/gps/$gps-portfolio'
      path: '/gps/$gps-portfolio'
      fullPath: '/gps/$gps-portfolio'
      preLoaderRoute: typeof GpsPortfolioPage
      parentRoute: typeof rootRoute
    }
    '/portfolio/$id': {
      id: '/portfolio/$id'
      path: '/portfolio/$id'
      fullPath: '/portfolio/$id'
      preLoaderRoute: typeof PortfolioIdImport
      parentRoute: typeof rootRoute
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardIndexImport
      parentRoute: typeof rootRoute
    }
    '/gps/': {
      id: '/gps/'
      path: '/gps'
      fullPath: '/gps'
      preLoaderRoute: typeof GpsIndexImport
      parentRoute: typeof rootRoute
    }
    '/history/': {
      id: '/history/'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryIndexImport
      parentRoute: typeof rootRoute
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginIndexImport
      parentRoute: typeof rootRoute
    }
    '/my-requests/': {
      id: '/my-requests/'
      path: '/my-requests'
      fullPath: '/my-requests'
      preLoaderRoute: typeof MyRequestsIndexImport
      parentRoute: typeof rootRoute
    }
    '/profile/': {
      id: '/profile/'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileIndexImport
      parentRoute: typeof rootRoute
    }
    '/record/': {
      id: '/record/'
      path: '/record'
      fullPath: '/record'
      preLoaderRoute: typeof RecordIndexImport
      parentRoute: typeof rootRoute
    }
    '/signup/': {
      id: '/signup/'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/history/$item': typeof HistoryItemRoute
  '/portfolio/$id': typeof PortfolioIdRoute
  '/dashboard': typeof DashboardIndexRoute
  '/gps': typeof GpsIndexRoute
  '/history': typeof HistoryIndexRoute
  '/login': typeof LoginIndexRoute
  '/my-requests': typeof MyRequestsIndexRoute
  '/profile': typeof ProfileIndexRoute
  '/record': typeof RecordIndexRoute
  '/signup': typeof SignupIndexRoute
  '/gps/$gps-portfolio': typeof GpsPortfolioPage
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/history/$item': typeof HistoryItemRoute
  '/portfolio/$id': typeof PortfolioIdRoute
  '/dashboard': typeof DashboardIndexRoute
  '/gps': typeof GpsIndexRoute
  '/history': typeof HistoryIndexRoute
  '/login': typeof LoginIndexRoute
  '/my-requests': typeof MyRequestsIndexRoute
  '/profile': typeof ProfileIndexRoute
  '/record': typeof RecordIndexRoute
  '/signup': typeof SignupIndexRoute
  '/gps/$gps-portfolio': typeof GpsPortfolioPage
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/history/$item': typeof HistoryItemRoute
  '/portfolio/$id': typeof PortfolioIdRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/gps/': typeof GpsIndexRoute
  '/history/': typeof HistoryIndexRoute
  '/login/': typeof LoginIndexRoute
  '/my-requests/': typeof MyRequestsIndexRoute
  '/profile/': typeof ProfileIndexRoute
  '/record/': typeof RecordIndexRoute
  '/signup/': typeof SignupIndexRoute
  '/gps/$gps-portfolio': typeof GpsPortfolioPage
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/history/$item'
    | '/portfolio/$id'
    | '/dashboard'
    | '/gps'
    | '/history'
    | '/login'
    | '/my-requests'
    | '/profile'
    | '/record'
    | '/signup'
    | '/gps/$gps-portfolio'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/history/$item'
    | '/portfolio/$id'
    | '/dashboard'
    | '/gps'
    | '/history'
    | '/login'
    | '/my-requests'
    | '/profile'
    | '/record'
    | '/signup'
    | '/gps/$gps-portfolio'
  id:
    | '__root__'
    | '/'
    | '/history/$item'
    | '/portfolio/$id'
    | '/dashboard/'
    | '/gps/'
    | '/history/'
    | '/login/'
    | '/my-requests/'
    | '/profile/'
    | '/record/'
    | '/signup/'
    | '/gps/$gps-portfolio'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HistoryItemRoute: typeof HistoryItemRoute
  PortfolioIdRoute: typeof PortfolioIdRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  GpsIndexRoute: typeof GpsIndexRoute
  HistoryIndexRoute: typeof HistoryIndexRoute
  LoginIndexRoute: typeof LoginIndexRoute
  MyRequestsIndexRoute: typeof MyRequestsIndexRoute
  ProfileIndexRoute: typeof ProfileIndexRoute
  RecordIndexRoute: typeof RecordIndexRoute
  SignupIndexRoute: typeof SignupIndexRoute
  GpsPortfolioPage: typeof GpsPortfolioPage
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HistoryItemRoute: HistoryItemRoute,
  PortfolioIdRoute: PortfolioIdRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  GpsIndexRoute: GpsIndexRoute,
  HistoryIndexRoute: HistoryIndexRoute,
  LoginIndexRoute: LoginIndexRoute,
  MyRequestsIndexRoute: MyRequestsIndexRoute,
  ProfileIndexRoute: ProfileIndexRoute,
  RecordIndexRoute: RecordIndexRoute,
  SignupIndexRoute: SignupIndexRoute,
  GpsPortfolioPage: GpsPortfolioPage,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/history/$item",
        "/portfolio/$id",
        "/dashboard/",
        "/gps/",
        "/history/",
        "/login/",
        "/my-requests/",
        "/profile/",
        "/record/",
        "/signup/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/history/$item": {
      "filePath": "history/$item.tsx"
    },
    "/portfolio/$id": {
      "filePath": "portfolio/$id.tsx"
    },
    "/dashboard/": {
      "filePath": "dashboard/index.tsx"
    },
    "/gps/": {
      "filePath": "gps/index.tsx"
    },
    "/history/": {
      "filePath": "history/index.tsx"
    },
    "/login/": {
      "filePath": "login/index.tsx"
    },
    "/my-requests/": {
      "filePath": "my-requests/index.tsx"
    },
    "/profile/": {
      "filePath": "profile/index.tsx"
    },
    "/record/": {
      "filePath": "record/index.tsx"
    },
    "/signup/": {
      "filePath": "signup/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
